version: "3.5"

services:
  db:
    image: postgres
    env_file: ".db.env"
    container_name: comic_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: docker/back/Dockerfile
    container_name: comic_backend
    env_file:
      - ".db.env"
      - ".back.env"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: